### ISSUE TITLE
Join us in fighting covid as an iPXE expert

### ISSUE THREAD

**Issue by sokoow** [pojntfx/ipxebuilderd#17]
Hey,

Cool project, it ideally looks like you'd be able to help us with fighting COVID with it!

We're planning to use a lot of iPXE related things, and your expertise would be really useful for us.

Join us on: https://devpost.com/software/help-education-sector-to-produce-more-laptops-for-students

Greetings, Karol & the team.

**Comment by pojntfx** [comment]
@sokoow Sorry for taking some time, I was caught up with work!

I'd be more than happy to help you with iPXE related stuff; although I don't consider myself an iPXE expert (I'm just a user after all) ;)

You might also be interested in some other PXEBoot/Network boot related projects that I've been working on:

- https://pojntfx.github.io/gon2n/ (L2 VPN)
- https://pojntfx.github.io/tftpdd/ (TFTP Server in Go)
- https://clusterplatform.github.io/clusterplatform/packages/provisioner/ (Complete OS deployment suite over TFTP, ISOs and even RPIs); I'm currently rewriting it in Go though ;))

**Comment by sokoow** [comment]
we've released a working alpha2 already: http://laptops.thereshope.eu/ check it out please :D

**Comment by sokoow** [comment]
Jesus dude, that https://clusterplatform.github.io/clusterplatform/packages/provisioner/ is pretty cool cosmic stuff - fair play to you :)

**Comment by pojntfx** [comment]
@sokoow I'll be sure to test this out over the weekend, but I'm still caught up with fighting COVID in another place - see https://github.com/pojntfx/nextcloud-talk-bot-framework ;)
